default:
  app:
    name: Wise Sayings API
    version: 1.0.0

  broker:
    mqtt:
      url: mqtt://test.mosquitto.org
      topics: ["wisesayingNeeded","wisesayingSent/#"]
      qos:
      protocol: mqtt
      retain:
      subscribe: true

development:

test:

staging:

production:
